# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# See https://pants.readme.io/docs/using-pants-in-ci for tips on how to set up your CI with Pants.

name: Pants linting and formatting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PANTS_CONFIG_FILES: pants.ci.toml
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: pantsbuild/actions/init-pants@v8
        with:
          # cache0 makes it easy to bust the cache if needed
          gha-cache-key: cache4-py${{ matrix.python_version }}
          named-caches-hash: ${{ hashFiles('build-support/lockfiles/*.lock') }}

      - name: Bootstrap Pants
        run: |
          pants --version

      - name: Check BUILD files
        run: |
          pants update-build-files --check

      - name: Lint and (TODO) typecheck
        run: |
          pants lint ::

      - name: Package/Run smoke test
        run: |
          pants package examples/python::
          pants run examples/python/helloworld:helloworld-pex

      - name: Upload pants log
        uses: actions/upload-artifact@v2
        with:
          name: pants-log
          path: .pants.d/pants.log
        if: always() # We want the log even on failures.
